// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8QuaWy0fae08yJgsDt2Z1V3VdraL23y4',
    appId: '1:1010269244937:web:63a4959b627c80503e72d8',
    messagingSenderId: '1010269244937',
    projectId: 'fir-project-40f91',
    authDomain: 'fir-project-40f91.firebaseapp.com',
    databaseURL: 'https://fir-project-40f91-default-rtdb.firebaseio.com',
    storageBucket: 'fir-project-40f91.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoIr75pNvajuWIdQ6GxoA47bfpCmbDYZw',
    appId: '1:1010269244937:android:d8872506435f9d0f3e72d8',
    messagingSenderId: '1010269244937',
    projectId: 'fir-project-40f91',
    databaseURL: 'https://fir-project-40f91-default-rtdb.firebaseio.com',
    storageBucket: 'fir-project-40f91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnTwlx20HOLGXCf3RNNiYBnukpyOqix44',
    appId: '1:1010269244937:ios:82d11f7081339bad3e72d8',
    messagingSenderId: '1010269244937',
    projectId: 'fir-project-40f91',
    databaseURL: 'https://fir-project-40f91-default-rtdb.firebaseio.com',
    storageBucket: 'fir-project-40f91.appspot.com',
    iosClientId: '1010269244937-dhmodkmgi06b2frjb8ibs3aotqo06eee.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnTwlx20HOLGXCf3RNNiYBnukpyOqix44',
    appId: '1:1010269244937:ios:82d11f7081339bad3e72d8',
    messagingSenderId: '1010269244937',
    projectId: 'fir-project-40f91',
    databaseURL: 'https://fir-project-40f91-default-rtdb.firebaseio.com',
    storageBucket: 'fir-project-40f91.appspot.com',
    iosClientId: '1010269244937-dhmodkmgi06b2frjb8ibs3aotqo06eee.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseProject',
  );
}
